name: test workflows
on: [workflow_dispatch]

env:
  image: 'checkmk/check-mk-raw:2.1.0p29'
  source_path: '/opt/omd/versions/2.1.0p29.cre/share/check_mk/agents/check-mk-agent_2.1.0p29-1_all.deb'
  destination_path: 'packages'

jobs:
  extract-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'develop' # Testing

      - name: Extract
        run: |
          container_id=$(docker create "$image")
          docker cp "$container_id:$source_path" "$destination_path"

      - name: Create Slackware package
        run: |
          docker run -it --rm -v $(pwd)/:/build vbatts/slackware:latest sh /build/source/compile_docker.sh

      - name: Push File
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add packages/check_mk_agent-"$(date +'%Y.%m.%d')".tgz packages/check_mk_agent-"$(date +'%Y.%m.%d')".tgz.md5
          git commit -m "Add check_mk_agent test version 2.1.0p29"
      - name: Push changes
        uses: ad-m/github-push-action@master
