name: test workflows
on: [workflow_dispatch]

env:
  image: 'checkmk/check-mk-raw'
  version_file: 'version_21'
  plugin_file: 'check_mk_agent.plg'
  destination_path: 'check_mk_agent'

jobs:
  extract-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'develop' # Testing

      - name: fetch latest check_mk agent image
        run : |
          current_version=$(cat $version_file)
          latest_version=$(curl -s https://hub.docker.com/v2/repositories/checkmk/check-mk-raw/tags\?page_size\=1000 | jq -r '.results[].name' | grep -oP "2\.1\.0p\d+" | sort -V | tail -n 1)

          if [[ "$latest_version" > "$current_version" ]]; then
              echo "New version found: $latest_version"
               echo "$latest_version" > $version_file
              echo "latest_version=$(echo $latest_version)" >> $GITHUB_ENV
          else
              echo "No new version found."
              exit 0
          fi

      - name: Extract
        run: |
          container_id=$(docker create "$image:$latest_version")
          docker cp "$container_id:/opt/omd/versions/$latest_version.cre/share/check_mk/agents/check-mk-agent_$latest_version-1_all.deb" "$destination_path"

      - name: Create Slackware package
        run: |
          docker run --rm -v $(pwd)/:/build vbatts/slackware:latest sh /build/source/compile_docker.sh

      - name: Update plugin file
        run: |
          md5_hash=$(md5sum packages/check_mk_agent-"$(date +'%Y.%m.%d')".tgz | cut -d' ' -f1)
          sed -i 's/<!ENTITY version   "[^"]*">/<!ENTITY version   "'$(date +'%Y.%m.%d')'">/' $plugin_file
          sed -i 's@<!ENTITY md5       "[^"]*">@<!ENTITY md5       "'"${md5_hash}"'">@' $plugin_file
          sed -i "/<CHANGES>/{n;s/.*/\n###$(date +'%Y.%m.%d')\n- Bumped checkmk_agent to $latest_version\n&/}" $plugin_file
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with: 
          commit-message: Bump check_mk_agent to $latest_version
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: bump-$latest_version
          delete-branch: true
          title: 'Check_mk_agent to $latest_version'
          body: |
            Bump Checkmk agent to $latest_version
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
          labels: |
            automated pr
          assignees: Donimax
          reviewers: Donimax

      # - name: Push File
      #   run: |
      #     git config --global user.name 'GitHub Action'
      #     git config --global user.email 'action@github.com'
      #     git add packages/check_mk_agent-"$(date +'%Y.%m.%d')".tgz packages/check_mk_agent-"$(date +'%Y.%m.%d')".tgz.md5 $version_file $plugin_file
      #     git commit -m "Add check_mk_agent test $latest_version"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: ${{ github.ref }}
